dist: trusty
sudo: false
language: ruby
notifications:
  email: false
env:
  - RELEASE_TAG="release-$TRAVIS_BUILD_NUMBER"
if: tag IS blank

branches:
  only:
    - master
jobs:
  include:
    - stage: build and publish
      language: java
      jdk: openjdk11
      install: skip
      script: ./gradlew clean build
      before_deploy:
        - git config --local user.name "Travis CI"
        - git config --local user.email "travis@example.com"
        - git tag -f $RELEASE_TAG
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: "build/libs/pal-tracker.jar"
        skip_cleanup: true
        on:
          tags: true
    - stage: deploy to cf
      language: bash
      script:
        - echo "Downloading $RELEASE_TAG"
        - wget -P build/libs https://github.com/SanjeetChoudhary/pal-tracker/tree/master/build/libs/pal-tracker.jar
    env:
      global:
        - CF_API= $CF_API_URL
        - CF_ORGANIZATION= $CF_ORG
        - CF_USERNAME= $CF_USERNAME
        - CF_PASSWORD= $CF_PASSWORD
        - CF_SPACE= $CF_SPACE
      before_deploy:
        - echo "Deploying $RELEASE_TAG to Cloud Foundry"
        - find . -type f -perm 0444
        - export CF_TRACE=true
      deploy:
        provider: cloudfoundry
        api: $CF_API_URL
        username: $CF_USERNAME
        password: $CF_PASSWORD
        organization: $CF_ORG
        space: $CF_SPACE
        manifest: manifest.yml       # (optional)  Defaults to manifest.yml.
        app_name: pal-tracker
      script: ./cf login -a=$CF_API -s=$CF_SPACE -o=$CF_ORGANIZATION -u=$CF_USERNAME -p=$CF_PASSWORD
#      deploy:
#        # 1. TO STAGING SPACE (continuously deploy here):
#        - provider: script
#          skip_cleanup: true
#          script: env CF_SPACE=development CF_APP_NAME=pal-tracker CF_MANIFEST=manifest.yml ci/deploy_to_cf.sh
#
